### ISSUE TITLE
Rounded objects do not always render smoothly and leave "dimples" when exported to STL, AMF, OBJ file formats

### ISSUE THREAD

**Issue by livetoski78** [davesrocketshop/Rocket#25] opened 2022-03-23 17:11 UTC
It's hard to describe this, so I added some pictures to illustrate.  This seems to be an issue that occurs when creating an object with multiple compound radii.  You can see in the first picture that the leading edge and trailing edge of the fins (airfoil shaped) show some artifacts rather than smooth lines in FreeCAD.  In the second picture, I have loaded an exported STL of a nose cone into Cura and the "dimples" are clearly visible on the side of the nose cone.  I have confirmed this happens when exporting to OBJ and AMF file formats, as well, albeit the "dimple" pattern is slightly different.  So far, I have been able to smooth them with filler and sanding, but it's a lot of extra work...you can't just print a piece, clean up the edges, and go.

Note: for the nose cones, it appears to affect Von Karman and Haack, but not ogive.

![image](https://user-images.githubusercontent.com/42725763/159755692-50e5a576-b85f-488f-b690-4497e253a102.png)

![image](https://user-images.githubusercontent.com/42725763/159755788-377ee9bd-7be3-482d-9bd1-7dabb0c3354a.png)

**Comment by davesrocketshop** [comment] 2022-03-23 17:44
Generally speaking, I don't worry too much about renders. They're display artifacts and occur under a variety of conditions within FC. The underlying model may not be the problem. That being said, it's worth investigating if you can share your model.

The dimpling is potentially more serious. It may be a problem with the mesh generation, so may also have a simple work around using the Mesh workbench. Again if you are willing to share your model I can investigate.

Additional information that would be helpful:
1. Your FreeCAD version information. You can get this by going to 'Help -> About FreeCAD', selecting 'Copy to Clipboard' pasting it here.
2. Cura version information. This is displayed on the splash screen when you start up, or from the 'Help -> About' menu

Thanks for reporting this.

**Comment by davesrocketshop** [comment] 2022-03-23 19:42
After some experimentation, I've found an export setting that can help significantly. The problem is not the model, but the granularity of the default mesh generated when exporting. Consider this example:

![Artifacts](https://user-images.githubusercontent.com/38090157/159781850-c35cee2d-906f-4a1c-b4ef-9fbb0ed10d37.png)

The nose on the left used the default export parameters. The one on the right was generated after adjusting the maximum mesh deviation. You can do this by selecting 'Edit -> Preferences...'. Select 'Import-Export' in the left hand column, and then the 'Mesh Formats' tab at the top. Decrease the size of 'Maximum mesh deviation'. For this option, the trade off is that as you decrease the deviation, you increase both the memory requirements and the compute time. For more square objects, this isn't really required, but for rounded objects it can make a big difference. This is the setting I used:

![ArtifactExport](https://user-images.githubusercontent.com/38090157/159782606-92aa2c69-1629-4eba-ab76-45ca49dda6cd.png)

**Comment by livetoski78** [comment] 2022-03-23 22:58
> Generally speaking, I don't worry too much about renders. They're display artifacts and occur under a variety of conditions within FC. The underlying model may not be the problem. That being said, it's worth investigating if you can share your model.
> 
> The dimpling is potentially more serious. It may be a problem with the mesh generation, so may also have a simple work around using the Mesh workbench. Again if you are willing to share your model I can investigate.
> 
> Additional information that would be helpful:
> 
> 1. Your FreeCAD version information. You can get this by going to 'Help -> About FreeCAD', selecting 'Copy to Clipboard' pasting it here.
> 2. Cura version information. This is displayed on the splash screen when you start up, or from the 'Help -> About' menu
> 
> Thanks for reporting this.

FreeCAD v0.19.3
Cura v4.12.1

**Comment by livetoski78** [comment] 2022-03-23 23:02
> After some experimentation, I've found an export setting that can help significantly. The problem is not the model, but the granularity of the default mesh generated when exporting. Consider this example:
> 
> ![Artifacts](https://user-images.githubusercontent.com/38090157/159781850-c35cee2d-906f-4a1c-b4ef-9fbb0ed10d37.png)
> 
> The nose on the left used the default export parameters. The one on the right was generated after adjusting the maximum mesh deviation. You can do this by selecting 'Edit -> Preferences...'. Select 'Import-Export' in the left hand column, and then the 'Mesh Formats' tab at the top. Decrease the size of 'Maximum mesh deviation'. For this option, the trade off is that as you decrease the deviation, you increase both the memory requirements and the compute time. For more square objects, this isn't really required, but for rounded objects it can make a big difference. This is the setting I used:
> 
> ![ArtifactExport](https://user-images.githubusercontent.com/38090157/159782606-92aa2c69-1629-4eba-ab76-45ca49dda6cd.png)

Interesting, your preferences right side menu is different than mine.  I don't have the tab for Mesh Formats in my version (0.19.3).
![image](https://user-images.githubusercontent.com/42725763/159810412-e6ee4afc-ab7a-416f-8780-9087882eac6c.png)

**Comment by davesrocketshop** [comment] 2022-03-24 00:38
Apologies. That's me being an idiot. I've been testing the pre-release version and used that one by mistake.

You can still do this, but you have to go through the Mesh workbench. From the workbench select the part, and then select 'Meshes -> Create mesh from shape...". You'll see a dialog on the left with a few more options. This is what I used:

![ArtifactMesh](https://user-images.githubusercontent.com/38090157/159819071-a18e9c73-df45-44d0-b74d-764678a1b2cb.png)

Then select the generated mesh and 'File->Export..."

**Comment by davesrocketshop** [comment] 2022-03-24 01:11
Again, me being an idiot. The preference I showed is available in 0.19, but workbench options only show up after the workbench has been opened.

Switch to the Mesh Design workbench. You can do this from the main screen... it's not necessary to open a project. This will allow you to see the mesh options in the preferences as I showed earlier.

**Comment by livetoski78** [comment] 2022-03-24 01:29
Thanks Dave!, Yep, I figured it out (load the Mesh Workbench first) just before I saw this.  It's a good hack to know, as I also posted it to a Facebook group I belong to for printed rocketry.  Apparently, I'm not the only one that has run into this dimpling issue.

**Comment by davesrocketshop** [comment] 2022-03-24 02:11
Share the wealth :)

I'll close this issue out then.

**Closed as completed by davesrocketshop** 2022-03-24 02:11 UTC
Labels: question
