### ISSUE TITLE
The width of the number input fields is too short.

### ISSUE THREAD

**Issue by BlindDuck** [davesrocketshop/Rocket#29] opened 2022-05-16 06:42 UTC
The width of the number input fields is too short.
The green "checked icon", the unit and the values after the ./,## are displayed only, but not the leading ones.

[code]
OS: openSUSE Leap 15.3 (KDE//usr/share/xsessions/kde-plasma)
Word size of FreeCAD: 64-bit
Version: 0.20.28861 (Git)
Build type: Release
Branch: master
Hash: 4fea37b3bc5a3a9fce789dac6d2444f240bd3313
Python 3.6.15, Qt 5.12.7, Coin 3.1.3, OCC 7.3.0
Locale: German/Germany (de_DE)
Installed mods:
  * Rocket 2.4.1
  * ThreadProfile 1.81.0
  * A2plus 0.4.56
  * Assembly4 0.11.12
[/code]

![ValueFieldWidth_20220516_083915](https://user-images.githubusercontent.com/24966241/168533798-6875691f-bb0e-416d-8de2-75d5b469f466.png)

**Comment by davesrocketshop** [comment] 2022-05-17 13:59
I'm not sure what's happening here, and it's not something I'm able to reproduce. The fields in your display do not appear to be following my size specifications, which is a fixed size field 100px in size. I can change that to a minimum size spec, and probably will, but that still doesn't explain what you're seeing and may not fix it.

It appears you have a preference pack applied. I'm not sure if that would cause the problems or not. I would suggest to revert to the default UI settings and seeing if that solves the problem. If it does, we can work from there.

**Comment by BlindDuck** [comment] 2022-05-17 15:22
I only compiled from git and did not change any setting right now.
The screen size is 4k (3840x2160).
Please verify with your settings to pin point it further.
![GUIPacks_20220517_171834](https://user-images.githubusercontent.com/24966241/168847611-8c76c665-a204-411d-84bf-4f4e348b29c2.png)

**Comment by davesrocketshop** [comment] 2022-05-17 17:32
I'm sorry, but I'm just not able to reproduce it. I've tried matching the settings to yours, including the language in case that had some significance.

I'm noticing some discrepancies between your settings and what is being displayed. For example, the 'No stylesheet' setting should normally produce the light colour backgrounds, not the dark colour. Your icons also seem smaller, but that may be difference in screen size. I've used the latest daily build, but you might have some differences having built from source.

It may well be screen size. Mine maxes out at 2560x1440, so I can't change to match yours. Can you try yours at the lower resolution?

If that turns out to be the problem, it should be fixed by changing the width from a fixed width to a minimum width.

**Comment by BlindDuck** [comment] 2022-05-27 06:35
I took some screen shoots (Windows/Linux, Part Design/Rocket) on a HP X2 1013 G3 (3000x2000).
The Windows versions info of FreeCAD is:
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.27422 (Git)
Build type: Release
Branch: master
Hash: d938733eaf2c2ce7cb18d1cbb56147185c473530
Python version: 3.8.6+
Qt version: 5.15.2
Coin version: 4.0.1
OCC version: 7.5.3
Locale: German/Germany (de_DE)

The Part Design fields look the same but not the Rocket ones.
With lower resolution it got worse, only the green checked icon is visible.

![2022-05-26 12_20_48-FreeCAD 0 20_Win10_2974x1894](https://user-images.githubusercontent.com/24966241/170644047-52d68938-82ab-4ece-9997-645ff7364895.png)
![Screenshot_20220526_123441_Linux](https://user-images.githubusercontent.com/24966241/170644212-1850f987-4b6c-4220-b121-9a80abac24a6.png)
![Screenshot_20220526_123602_LinuxPartDesign](https://user-images.githubusercontent.com/24966241/170644217-186e2d55-debd-4820-9b36-c9c67e2b62b2.png)
![Screenshot_20220526_123820_Linux](https://user-images.githubusercontent.com/24966241/170644218-6e87e01c-f2e6-48e6-9b30-a8ca17fbee82.png)
![2022-05-26 12_22_57-FreeCAD 0 20](https://user-images.githubusercontent.com/24966241/170646394-2c24b015-d285-465c-943c-a7a77789c2d4.png)
.

**Comment by davesrocketshop** [comment] 2022-07-15 17:04
Merged

**Closed as completed by davesrocketshop** 2022-07-15 17:04 UTC
Labels: bug, question
